#locale
plugin-prefix: "<white>[<#ff6969>S<#ffb169>i<#fff569>m<#c3ff69>p<#82ff69>l<#69ff98>e<#69f5ff>D<#6987ff>y<#7869ff>e<reset><white>]</white> <gray>»</gray>"
error-not-a-player: "<plugin_prefix> <red>Sorry, only a player can run this command!"
error-no-permission: "<plugin_prefix> <red>Sorry, you do not have permission to use this command"
error-invalid-command: "<plugin_prefix> <red>Sorry, the command or arguments that you provided were invalid. Please check your spelling and/or usage and try again"
error-no-arguments: "<plugin_prefix> <red>Sorry, you must provide an argument. Please check your usage and try again"
error-item-not-basic-dyable: "<plugin_prefix> <red>Sorry, <item> is not dyable. Please hold a dyable item and try again"
error-item-not-hex-dyable: "<plugin_prefix> <red>Sorry, <item> is not dyable with a hex code. Please hold a dyable item and try again"
error-invalid-hex-code: "<plugin_prefix> <red>Sorry, <input> is not a valid hex code, please use the <yellow>#ABC123</yellow> format for hex codes"
error-invalid-dye-color: "<plugin_prefix> <red>Sorry, <input> is not one of the named dye colors. Please check your spelling and try again"
command-output-basic-dye-success: "<plugin_prefix> <color><color_name> <green>dye successfully applied"
command-output-rgb-dye-success: "<plugin_prefix> <color><color_name> <green>colored dye successfully applied"
command-output-default: "<plugin_prefix> <gray>Please do <aqua>/dye</aqua> <<blue>basic</blue>|<blue>rgb</blue>> <<yellow>color</yellow>|<yellow>#abc123</yellow>>"
config-reloaded: "<plugin_prefix> <gold>Simple Dye Config reloaded!"