#Dyable items: (note, you can only put items that are tagged as dyable can be used here)
basic:
  - LEATHER_BOOTS
  - LEATHER_LEGGINGS
  - LEATHER_CHESTPLATE
  - LEATHER_HELMET
  - LEATHER_HORSE_ARMOR
  - WOLF_ARMOR
hex-dye:
  - LEATHER_BOOTS
  - LEATHER_LEGGINGS
  - LEATHER_CHESTPLATE
  - LEATHER_HELMET
  - LEATHER_HORSE_ARMOR
  - WOLF_ARMOR