name: SimpleDye
version: '${project.version}'
main: adhdmc.simpledye.SimpleDye
api-version: 1.19
authors: [ Peashooter101, Rhythmic ]
description: Simple Dye for Leather and other dyable items.
permissions:
  sd.reload:
    description: Allow the player to reload configuration
    default: op
  sd.dye.basic:
    description: Allow simple dyeing of leather armor.
    usage: /<command> simple [color]
    default: op
  sd.dye.rgb:
    description: Allow rgb dyeing of leather armor using hex colors.
    usage: /<command> rgb [#RRGGBB|RRGGBB]
    default: op
  sd.*:
    description: Wildcard permission.
    usage: /<command>
    default: op
commands:
  sd:
    description: Simple Dyeing Command
    aliases:
      - simpledye
      - dye
    permission-message: You do not have permission.
    usage: /<command> [simple|rgb]
  sdreload:
    description: Reloads SimpleDye configuration
    permission: simpledye.reload